/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "PTNextVPC": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "SessionStore": {
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Redis"
      "username": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}